# Generated by Django 6.0.2 on 2026-03-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='habit_type',
            field=models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative')], default='positive', max_length=10),
        ),
    ]
