# Generated by Django 6.0.2 on 2026-03-09 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_logentry'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='logentry',
            name='unique_log_per_habit_per_date',
        ),
        migrations.AlterUniqueTogether(
            name='logentry',
            unique_together={('habit', 'date')},
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='logentry',
            name='created_at',
        ),
    ]
